In [1]:
#feature scaling-->min max normalization
#x(scaled)=(i)-x(min)/x(max)-x(min)

In [2]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (from scikit-learn) (2.5.1)
Requirement already satisfied: scipy>=1.10.0 in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (from scikit-learn) (2.24.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\users\asus\onedrive\desktop\ml workshop\ml_workshop_env\lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
import numpy as np
import pandas as pd
import sklearn

In [9]:
# now create the table
data = pd.DataFrame({
    'Price_USA': [80, 50, 140, 25],
    'Price_INR': [5000, 7000, 12000, 3000]
})

data

   Price_USA  Price_INR
0         80       5000
1         50       7000
2        140      12000
3         25       3000

In [11]:
# perfrom mathematicall wise
data['Price_USA_minmax'] = (data['Price_USA']-data['Price_USA'].min())/(data['Price_USA'].max()-data['Price_USA'].min())
data

   Price_USA  Price_INR  Price_USA_minmax
0         80       5000          0.478261
1         50       7000          0.217391
2        140      12000          1.000000
3         25       3000          0.000000

In [13]:
# Perform Min-Max Normalization for Price_INR
data['Price_INR_minmax'] = ( data['Price_INR'] - data['Price_INR'].min()) / ( data['Price_INR'].max() - data['Price_INR'].min())
data

   Price_USA  Price_INR  Price_USA_minmax  Price_INR_minmax
0         80       5000          0.478261          0.222222
1         50       7000          0.217391          0.444444
2        140      12000          1.000000          1.000000
3         25       3000          0.000000          0.000000

In [14]:
import sklearn

In [16]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [17]:
min_max =MinMaxScaler()

In [19]:
# nedd to use fit_transform()
data['Price_USA_minsk'] = min_max.fit_transform(data[['Price_USA']])
data

   Price_USA  Price_INR  Price_USA_minmax  Price_INR_minmax  Price_USA_minsk
0         80       5000          0.478261          0.222222         0.478261
1         50       7000          0.217391          0.444444         0.217391
2        140      12000          1.000000          1.000000         1.000000
3         25       3000          0.000000          0.000000         0.000000

In [20]:
data['Price_INR_minsk'] = min_max.fit_transform(data[['Price_INR']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk
0,80,5000,0.478261,0.222222,0.478261,0.222222
1,50,7000,0.217391,0.444444,0.217391,0.444444
2,140,12000,1.000000,1.000000,1.000000,1.000000
3,25,3000,0.000000,0.000000,0.000000,0.000000

In [37]:
# STANDARD SACLLIN ( z = x(i)-mue/sigma)
data['Price_USA_std'] = (data['Price_USA']-data['Price_USA'].mean())/(data['Price_USA'].std())
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947

In [38]:
data['Price_INR_std'] = (data['Price_INR']-data['Price_INR'].mean())/(data['Price_INR'].std())
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947

In [39]:
from sklearn.preprocessing import StandardScaler

In [43]:
scaler = StandardScaler()

In [44]:
data['Price_USA_scaler'] = scaler.fit_transform(data[['Price_USA']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_scaler
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815

In [45]:
data['Price_INR_scaler'] = scaler.fit_transform(data[['Price_INR']])
data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_scaler,Price_INR_scaler
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617,-0.523205
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346,0.074744
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544,1.569614
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815,-1.121153

In [46]:
from sklearn.preprocessing import RobustScaler

In [53]:
robust = RobustScaler()

In [54]:
data['Price_USA_robust'] = robust.fit_transform(data[['Price_USA']])

data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_scaler,Price_INR_scaler,Price_USA_robust
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617,-0.523205,0.292683
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346,0.074744,-0.292683
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544,1.569614,1.463415
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815,-1.121153,-0.780488

In [55]:
data['Price_INR_robust'] = robust.fit_transform(data[['Price_INR']])

data

,Price_USA,Price_INR,Price_USA_minmax,Price_INR_minmax,Price_USA_minsk,Price_INR_minsk,Price_USA_std,Price_INR_std,Price_USA_scaler,Price_INR_scaler,Price_USA_robust,Price_INR_robust
0,80,5000,0.478261,0.222222,0.478261,0.222222,0.126108,-0.453108,0.145617,-0.523205,0.292683,-0.266667
1,50,7000,0.217391,0.444444,0.217391,0.444444,-0.479212,0.064730,-0.553346,0.074744,-0.292683,0.266667
2,140,12000,1.000000,1.000000,1.000000,1.000000,1.336748,1.359325,1.543544,1.569614,1.463415,1.600000
3,25,3000,0.000000,0.000000,0.000000,0.000000,-0.983645,-0.970947,-1.135815,-1.121153,-0.780488,-0.800000

In [57]:
data['Price_USA_robust'] = robust.fit_transform(data[['Price_USA']])

data['Price_USA_robust']

0    0.292683
1   -0.292683
2    1.463415
3   -0.780488
Name: Price_USA_robust, dtype: float64

In [58]:
data['Price_INR_robust'] = robust.fit_transform(data[['Price_INR']])

data['Price_INR_robust']

0   -0.266667
1    0.266667
2    1.600000
3   -0.800000
Name: Price_INR_robust, dtype: float64

In [ ]:
# Regression on a case study related to predecting Miles per gallon(mpg)